name: Generate Release Notes

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get the current date
        id: date
        run: echo "DATE=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Generate tag
        id: tag
        run: echo "TAG=v${{ env.DATE }}" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Generate release notes
        id: notes
        run: |
          NOTES=$(git log -1 --pretty=format:"%s")
          echo "NOTES=$NOTES" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: ${{ env.NOTES }}
          draft: false
          prerelease: true
